services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=mariadb
      - TZ=Asia/Tokyo

volumes:
  db_data:
